language: objective-c
xcode_workspace: radiant-player-mac.xcworkspace
xcode_scheme: Radiant Player
osx_image: xcode10.1

cache:
  - bundler
  - cocoapods

before_script:
  - mkdir -p ~/go
  - mkdir -p ~/bin
  - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod +x ~/bin/gimme
  - eval "$(~/bin/gimme 1.11.2)"
  - go get github.com/aktau/github-release

script:
  - set -o pipefail && xcodebuild -workspace radiant-player-mac.xcworkspace -scheme Radiant\ Player build | xcpretty

after_success:
  - PATH=$GOPATH/bin:$PATH ./scripts/release-app.sh
  - ./scripts/build-website.sh && ./scripts/deploy-website.sh

env:
  global:
    - GOPATH=~/go
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speedup for html-proofer
    - GITHUB_USER=radiant-player
    - GITHUB_REPO=radiant-player-mac
    - GITHUB_BOT_USER=radiant-bot
    - GITHUB_BOT_EMAIL=jacobwgillespie+radiant-bot@gmail.com
    # GITHUB_TOKEN=encrypted
    - secure: "R6R1/PzW9F7lemz5CpKvlVl4DxSYn3wPUJdeCme/QyJ0IG/NQd76C8+BgIyH2NjiCwTlSjRmez91EQck8ostUgO4k7ApsCt1Ge4y+YEPs9sZy3J2Y0i8I38x7vsKQ+g7f/70g01y8vZ0d90QL1jADZ3vEQB2bEfBY24DzIUs8Rdlv161FuBM6bplGZLrvg0MNBkpyqE70CxzxMZtxSt16GLgcoZEw76212n1SbCv3mxIHMULY6rOXsPZ7r+0U7etU4WKJLJNtBfG8Hkeamf6Y9eWUFqyfdHkIfDaTrQfl8Zcs4RqOFnBs07oCvEAP279yPPK4EacOXizliPemYnylVKfBRkEok3KrG9aWzkqvJ9TzyQPS5GYLTKgO821Le0FCXpgD/mYgGFWZm62PCpy1FgHS9WSi/ypaT2Z/O9dtUTcoyypz0z06wEupl6D18yAsHE06mT5xK+LKXDKydeGoSm8WYUtKr2SRK/FaHZ82VyEVamK7G3m9k3paSj0omVvoY3bYtlLTrd5Ko81IKqjByir7akGkL6/Kvfi6sBdFoRkR53EdrBAbvhJ3QuDxmSl9Wq9AKHrk8q1Yg3TwC4LiE2EAJ7Kk/9mlGVes2nirL7GZii1LNCy5zAXfTnM5XHVcwPXmVSplrauwRsfvRJJqF08i63BTunEIMKPd6Gi214="
    # KEY_PASSWORD=encrypted
    - secure: "drkqA6GFiKly3wayztgXlco4g1PAVX4LjowBHNyT8MYUHUBEMcSMsED+2MD2nmWKjuuGGi1jBMVgv7LiMrJmO8KTjAhE9PUjOXIZm/T3/m/yhzLXYs0FiMN7AtZ6MSSbd+kfks51oBuZJxdvM42Obwg7LQmJstMRY4Vlil9yXmuIrvVWDESU30+kWw81msuTYqpHw7D2JcBELz3dwaLV0P93H3l4Gr/opy/M8y+Aknxb9QBQYyx8jZA7mQHG4+N9VfhyzGlxncz8Bvr4jqSbQ6Dezwf7KV5Z6iGHHu2W67VTJY+LwGb0bG4p8hXlvJgwkoIwmC91RTDmY8VnktfTQsp0MJP+U41/aqf9xgLZmUVITEE5/3aDeAv7XtEsUL+tpT/2oVXXphHboLf60xYuiLFuYeIVhStergw/sY1xic/3wbScDxXp9Sosp0q6fc8QRdlfI9y0zLgl+CKig+NVI0Iq2rk+ufb5cWhGtFTY8x6bX1R2s5cUo7eUiVKp9xy9ElLdvSgi66BaMWL4uYY32ldVOxsI4sKEZUPpciexkg+D8RvxyO5G7y4t/35O7TUNHDq3nHbUs1H1Pmly9YZoFGFIrlo2XrgWyJQQniBwZlWkrVi+bfhPO44Go9PcXGgshBFWUKL6WlVCqQumDISENDJZRMpLV7JRo/fLqNuBhUw="
