language: objective-c
xcode_workspace: radiant-player-mac.xcworkspace
xcode_scheme: Radiant Player
osx_image: xcode7.1

cache:
  - bundler
  - cocoapods

before_script:
  - mkdir -p ~/go
  - mkdir -p ~/bin
  - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod +x ~/bin/gimme
  - eval "$(~/bin/gimme 1.5.2)"
  - go get github.com/aktau/github-release

after_success:
  - ./scripts/build-website.sh
  - ./scripts/deploy-website.sh

env:
  global:
    - GOPATH=~/go
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speedup for html-proofer
    - GITHUB_USER=radiant-player
    - GITHUB_REPO=radiant-player-mac
    - GITHUB_BOT_USER=radiant-bot
    - GITHUB_BOT_EMAIL=jacobwgillespie+radiant-bot@gmail.com
    # GITHUB_TOKEN=encrypted
    - secure: "d+viN4YvcYgARAvknJO2ymZf95Yu/xulCCxTPYsrTucm4knqQHdsO9NyvG7DHhDkNRPxbYXOSJfB4UGv6ObCSquvSA43XzS2nUSnfHvHyio/mcbH//DbrRTpUH7ziGJqfzXuwOmxS0DLwi20QG9+4amTo5tilet9FiqP3xfITT+Nm1awpfqMOoqaXZdVmJh2bj1hyCT92WmEBhepz7VdsVcdpUphO2jLtnE4EHIcUeJ7Fw3A2aqRnVbWfcy25Bmsp/aOzGRBH1zArRnZjaCUPK7OX+tnq7TnSztL8qeQIBqtMKriq45x4hFE9JTJW3iO+hv8LQB6xyrfIvzCisz6Rcwhwb5oMkO9ykYoFZHSy5nuCSZvnpIISdWFobV58EYLwu0GuKB6iW0zOO4bJYje9qdvzhh/h1o2sXho77pFLcmURjll8HdRTLSY1Ha3LRFeoYGBHf9K7RW1YKhVkGDqKyahjzijZ5MIETWkTgg8VICvJF2DlWLxax/j1kmhH+MjTV1wGaEPXTmcnBuEU3cNsFhv1SIzNP+8q97tuNKeBOL5rd1nOHH4uuO1z+LXA0ulmk7E8glcDftVsaW7WhvOPdwYIj5GFMKI6RmUIjcifIH+CR+8pAlXeR5Ek8pAYDhKpJlHpAH/QX0JT9+mLqiWIuMN7RG4tPKadrEVgWJKdxQ="
    # KEY_PASSWORD=encrypted
    - secure: "Ri/ZEL/kK14y/v6LmqIbuQ03yWR6r84ifnWab515OB5TS5RP4E071W6vQe/nB6KLIGKgQXLWnXhX+9df5WOYrwQGFOD8dqEG4c6PbxUXPFyimK2v5l4wWLHD73yyNhyGcTXYnG5dlL+n+815LPEfee60WVwJ8FKZrD2iJUXgYi7IT9xojz3+ZDOroIvccuRLt33Xh/Q8E25s6bJBzz4IujVoG+i5UbCQHp05QyKwG3RxB41oY4Yuc/1SF9LskGRq6YTh2/4ASnRj5cenQnKVkXj2CGBGtnUKVTjC6piE8iNLAuws3qXAJVhK+HLULaKyYhGS4LQNFvsZvJ07QrhNyI3SApvZv34G5/zVgQX1Dq64qyPEXazouhoSDPXXGw4KLDTr/1BVCHk2zvbv3AUsXls7CubOzBx+lle6y27FuQhTAmKN5rukWj781holTjlXTUS3UK8r/ely0VaHbkov40iq8esdmSQ3rxt35SZ2gMp/DvOO8pPSyU9OLttNdg4zOjy611JIOVcAFUPgH4o9ok2EX5SBE6kIeRnWjFYI3Pr7kj5dHxvxFQL+lpc54iQmGJdUAV9Ni5R2F2E1JY850qIiJ5MmsJg5eUA3FFJ+VVzzz9RbNSdj/ZSVQooHAq51TNfkWEP6GIDtC4vD/8FstHkOfK9c5EtDJD42z8jc9h4="
